In [1]:
import pandas as pd

In [2]:
c=pd.read_csv("customer_subscription_churn_usage_patterns.csv")
c

user_id signup_date plan_type  monthly_fee  avg_weekly_usage_hours  \
0           1  2023-04-15   Premium          699                     1.1   
1           2  2023-08-27   Premium          699                     2.6   
2           3  2023-10-12   Premium          699                    14.3   
3           4  2023-12-11     Basic          199                    17.6   
4           5  2023-02-14     Basic          199                     9.8   
...       ...         ...       ...          ...                     ...   
2795     2796  2023-03-10  Standard          399                     6.7   
2796     2797  2024-11-20  Standard          399                    11.0   
2797     2798  2024-08-13  Standard          399                    11.0   
2798     2799  2024-05-23   Premium          699                    15.0   
2799     2800  2024-03-21  Standard          399                     2.0   

      support_tickets  payment_failures  tenure_months  last_login_days_ago  \
0                   4                 1              8                   14   
1                   6                 0             35                    1   
2                   8                 3              2                   14   
3                   5                 2             11                    9   
4                   5                 2              6                   38   
...               ...               ...            ...                  ...   
2795                1                 1             21                   59   
2796                4                 0              6                    4   
2797                0                 4             22                   59   
2798                3                 4             25                   20   
2799                0                 1             12                    1   

     churn  
0      Yes  
1      Yes  
2      Yes  
3      Yes  
4      Yes  
...    ...  
2795    No  
2796    No  
2797    No  
2798    No  
2799   Yes  

[2800 rows x 10 columns]

In [3]:
c.columns[c.isna().any()]

Index([], dtype='object')

In [4]:
c.describe()

user_id  monthly_fee  avg_weekly_usage_hours  support_tickets  \
count  2800.000000  2800.000000             2800.000000      2800.000000   
mean   1400.500000   434.214286               12.891429         3.887857   
std     808.434702   205.678472                7.109691         2.606419   
min       1.000000   199.000000                0.500000         0.000000   
25%     700.750000   199.000000                6.700000         2.000000   
50%    1400.500000   399.000000               12.800000         4.000000   
75%    2100.250000   699.000000               19.200000         6.000000   
max    2800.000000   699.000000               25.000000         8.000000   

       payment_failures  tenure_months  last_login_days_ago  
count       2800.000000    2800.000000          2800.000000  
mean           2.491786      18.612857            30.005000  
std            1.691647      10.374487            17.852757  
min            0.000000       1.000000             0.000000  
25%            1.000000      10.000000            14.000000  
50%            2.000000      18.000000            30.000000  
75%            4.000000      27.000000            46.000000  
max            5.000000      36.000000            60.000000

In [5]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   user_id                 2800 non-null   int64  
 1   signup_date             2800 non-null   object 
 2   plan_type               2800 non-null   object 
 3   monthly_fee             2800 non-null   int64  
 4   avg_weekly_usage_hours  2800 non-null   float64
 5   support_tickets         2800 non-null   int64  
 6   payment_failures        2800 non-null   int64  
 7   tenure_months           2800 non-null   int64  
 8   last_login_days_ago     2800 non-null   int64  
 9   churn                   2800 non-null   object 
dtypes: float64(1), int64(6), object(3)
memory usage: 218.9+ KB


In [6]:
c=c.drop(["signup_date"],axis="columns")
c

user_id plan_type  monthly_fee  avg_weekly_usage_hours  support_tickets  \
0           1   Premium          699                     1.1                4   
1           2   Premium          699                     2.6                6   
2           3   Premium          699                    14.3                8   
3           4     Basic          199                    17.6                5   
4           5     Basic          199                     9.8                5   
...       ...       ...          ...                     ...              ...   
2795     2796  Standard          399                     6.7                1   
2796     2797  Standard          399                    11.0                4   
2797     2798  Standard          399                    11.0                0   
2798     2799   Premium          699                    15.0                3   
2799     2800  Standard          399                     2.0                0   

      payment_failures  tenure_months  last_login_days_ago churn  
0                    1              8                   14   Yes  
1                    0             35                    1   Yes  
2                    3              2                   14   Yes  
3                    2             11                    9   Yes  
4                    2              6                   38   Yes  
...                ...            ...                  ...   ...  
2795                 1             21                   59    No  
2796                 0              6                    4    No  
2797                 4             22                   59    No  
2798                 4             25                   20    No  
2799                 1             12                    1   Yes  

[2800 rows x 9 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le=LabelEncoder()
c["plan_type"]=le.fit_transform(c["plan_type"])
c["plan_type"]

0       1
1       1
2       1
3       0
4       0
       ..
2795    2
2796    2
2797    2
2798    1
2799    2
Name: plan_type, Length: 2800, dtype: int64

In [9]:
c

user_id  plan_type  monthly_fee  avg_weekly_usage_hours  \
0           1          1          699                     1.1   
1           2          1          699                     2.6   
2           3          1          699                    14.3   
3           4          0          199                    17.6   
4           5          0          199                     9.8   
...       ...        ...          ...                     ...   
2795     2796          2          399                     6.7   
2796     2797          2          399                    11.0   
2797     2798          2          399                    11.0   
2798     2799          1          699                    15.0   
2799     2800          2          399                     2.0   

      support_tickets  payment_failures  tenure_months  last_login_days_ago  \
0                   4                 1              8                   14   
1                   6                 0             35                    1   
2                   8                 3              2                   14   
3                   5                 2             11                    9   
4                   5                 2              6                   38   
...               ...               ...            ...                  ...   
2795                1                 1             21                   59   
2796                4                 0              6                    4   
2797                0                 4             22                   59   
2798                3                 4             25                   20   
2799                0                 1             12                    1   

     churn  
0      Yes  
1      Yes  
2      Yes  
3      Yes  
4      Yes  
...    ...  
2795    No  
2796    No  
2797    No  
2798    No  
2799   Yes  

[2800 rows x 9 columns]

In [10]:
le=LabelEncoder()
c["churn"]=le.fit_transform(c["churn"])
c["churn"]

0       1
1       1
2       1
3       1
4       1
       ..
2795    0
2796    0
2797    0
2798    0
2799    1
Name: churn, Length: 2800, dtype: int64

In [11]:
c

user_id  plan_type  monthly_fee  avg_weekly_usage_hours  \
0           1          1          699                     1.1   
1           2          1          699                     2.6   
2           3          1          699                    14.3   
3           4          0          199                    17.6   
4           5          0          199                     9.8   
...       ...        ...          ...                     ...   
2795     2796          2          399                     6.7   
2796     2797          2          399                    11.0   
2797     2798          2          399                    11.0   
2798     2799          1          699                    15.0   
2799     2800          2          399                     2.0   

      support_tickets  payment_failures  tenure_months  last_login_days_ago  \
0                   4                 1              8                   14   
1                   6                 0             35                    1   
2                   8                 3              2                   14   
3                   5                 2             11                    9   
4                   5                 2              6                   38   
...               ...               ...            ...                  ...   
2795                1                 1             21                   59   
2796                4                 0              6                    4   
2797                0                 4             22                   59   
2798                3                 4             25                   20   
2799                0                 1             12                    1   

      churn  
0         1  
1         1  
2         1  
3         1  
4         1  
...     ...  
2795      0  
2796      0  
2797      0  
2798      0  
2799      1  

[2800 rows x 9 columns]

In [12]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   user_id                 2800 non-null   int64  
 1   plan_type               2800 non-null   int64  
 2   monthly_fee             2800 non-null   int64  
 3   avg_weekly_usage_hours  2800 non-null   float64
 4   support_tickets         2800 non-null   int64  
 5   payment_failures        2800 non-null   int64  
 6   tenure_months           2800 non-null   int64  
 7   last_login_days_ago     2800 non-null   int64  
 8   churn                   2800 non-null   int64  
dtypes: float64(1), int64(8)
memory usage: 197.0 KB


In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
x=c[["plan_type","monthly_fee","avg_weekly_usage_hours","tenure_months"]]
y=c["churn"]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
x_train

plan_type  monthly_fee  avg_weekly_usage_hours  tenure_months
2401          0          199                    12.0             26
783           0          199                     8.4             20
48            1          699                    20.9              3
1034          1          699                     3.7             24
1550          2          399                     3.3             13
...         ...          ...                     ...            ...
1638          0          199                     1.5             10
1095          2          399                    22.2             23
1130          2          399                    11.4             27
1294          2          399                    16.5             30
860           2          399                     4.9             17

[2100 rows x 4 columns]

In [15]:
s=StandardScaler()
x_train=s.fit_transform(x_train)
x_train

array([[-1.23059792, -1.13958541, -0.12709483,  0.70687337],
       [-1.23059792, -1.13958541, -0.63346474,  0.12919764],
       [-0.00583222,  1.29740987,  1.12476413, -1.50755028],
       ...,
       [ 1.21893348, -0.1647873 , -0.21148982,  0.80315266],
       [ 1.21893348, -0.1647873 ,  0.50586756,  1.09199053],
       [ 1.21893348, -0.1647873 , -1.12576883, -0.15964023]],
      shape=(2100, 4))

In [16]:
x_test=s.transform(x_test)
x_test

array([[-0.00583222,  1.29740987, -1.22422964, -0.25591952],
       [-1.23059792, -1.13958541, -1.43521711, -1.02615383],
       [-0.00583222,  1.29740987, -0.94291303, -1.3149917 ],
       ...,
       [ 1.21893348, -0.1647873 , -0.39434562, -1.41127099],
       [ 1.21893348, -0.1647873 ,  1.34981742, -1.50755028],
       [-0.00583222,  1.29740987, -0.95697886, -0.25591952]],
      shape=(700, 4))

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
knn=KNeighborsClassifier(n_neighbors=5,metric="euclidean")
knn.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean')

In [19]:
y_pred=knn.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5214285714285715

In [21]:
import numpy as np
j=np.array([[1,699,12,26]])
jp=s.fit_transform(j)
jp


array([[0., 0., 0., 0.]])

In [22]:
# import numpy as np
# sso=np.array([[-1.23059792, -1.13958541, -0.12709483,  0.70687337],
#        [-1.23059792, -1.13958541, -0.63346474,  0.12919764],
#        [-0.00583222,  1.29740987,  1.12476413, -1.50755028],
#        [ 1.21893348, -0.1647873 , -0.21148982,  0.80315266],
#        [ 1.21893348, -0.1647873 ,  0.50586756,  1.09199053],
#        [ 1.21893348, -0.1647873 , -1.12576883, -0.15964023]])

In [23]:
#sso.mean()

In [24]:
#sso.std()