In [1]:
import numpy as np

In [2]:
# using arrays over list
#but arrays cae using numpy 
#1) continuous memory so accessing fast

#2)vectorization -no need loops
import numpy as np
a=np.array((1,2,3))
b=np.array([3,4,5])
print(a+b)

#3) maahematical operastions
np.sum(np.array([1,2,3,6]))

#4)memory storage less because list store references 


[4 6 8]


np.int64(12)

In [3]:
#array creation functions
# a=[1,2,3,4,5]
# type(a)
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [4]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [5]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(2,3)

array([[0.00160304, 0.82917902, 0.76426994],
       [0.39588642, 0.90784413, 0.80504275]])

In [10]:
[np.random.randint(2,6) for _ in range(5)]
np.random.randint(2,6,size=(2,3))

array([[3, 2, 4],
       [4, 3, 3]], dtype=int32)

In [11]:
np.random.randn(2,3)

array([[ 1.24673218,  0.07585541, -0.12227135],
       [ 0.87237529, -0.39831643, -1.11573928]])

In [12]:
#array properties
a.shape
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
b

2
(2, 3)
6
int64


array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# array reshaping
b.reshape((3,2))
b.reshape((-1,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
c=np.array([[2,3],[4,5]])
c1=c.flatten()
c1[0]=8
print(c)
print(c1)

[[2 3]
 [4 5]]
[8 3 4 5]


In [15]:
c=np.array([[2,3],[4,5]])
c1=c.ravel()
c1[0]=8
print(c)
print(c1)

[[8 3]
 [4 5]]
[8 3 4 5]


In [16]:
b=np.array([[1,2,3],[4,5,6]])
b[1][1]

np.int64(5)

In [17]:
d=np.array([[[1,4,6,7],[5,9,56,3]],[[2,34,78,1],[8,4,32,6]]])
d[1][0][3]

np.int64(1)

In [18]:
# indexing /slicing
d[:,1]

array([[ 5,  9, 56,  3],
       [ 8,  4, 32,  6]])

In [19]:
d[1:4]

array([[[ 2, 34, 78,  1],
        [ 8,  4, 32,  6]]])

In [20]:
# boolean filtering

d[d>10]

array([56, 34, 78, 32])

In [21]:
sa=np.array([[ 0.43934631, -0.84945494, -0.78472377],
       [-0.41975758, -0.26508408, -0.66358511]])
sa

array([[ 0.43934631, -0.84945494, -0.78472377],
       [-0.41975758, -0.26508408, -0.66358511]])

In [22]:
#statistics 
np.mean(sa)

np.float64(-0.4238765283333334)

In [23]:
np.std(sa)

np.float64(0.43573187405848807)

In [24]:
np.var(sa)

np.float64(0.18986226607052212)

In [25]:
np.median(sa)

np.float64(-0.541671345)

In [26]:
np.min(sa)

np.float64(-0.84945494)

In [27]:
np.max(sa)

np.float64(0.43934631)

In [28]:
np.percentile(10,100)

np.float64(10.0)

In [29]:
#aggregation
print(d)
np.sum(d,axis=0)#column-wise

[[[ 1  4  6  7]
  [ 5  9 56  3]]

 [[ 2 34 78  1]
  [ 8  4 32  6]]]


array([[ 3, 38, 84,  8],
       [13, 13, 88,  9]])

In [30]:
np.sum(d,axis=1)#row-wise

array([[  6,  13,  62,  10],
       [ 10,  38, 110,   7]])

In [31]:
np.random.seed(42)
np.random.normal(3,1)

3.496714153011233

In [32]:
#sorting
np.argsort(d)

array([[[0, 1, 2, 3],
        [3, 0, 1, 2]],

       [[3, 0, 1, 2],
        [1, 3, 0, 2]]])

In [33]:
np.sort(d)

array([[[ 1,  4,  6,  7],
        [ 3,  5,  9, 56]],

       [[ 1,  2, 34, 78],
        [ 4,  6,  8, 32]]])

In [34]:
np.vstack(d)

array([[ 1,  4,  6,  7],
       [ 5,  9, 56,  3],
       [ 2, 34, 78,  1],
       [ 8,  4, 32,  6]])

In [35]:
np.hstack(d)

array([[ 1,  4,  6,  7,  2, 34, 78,  1],
       [ 5,  9, 56,  3,  8,  4, 32,  6]])

In [36]:
#broadcasting
a = np.array([[1, 2, 3],
              [4, 5, 6]]) # Shape (2, 3)
b = np.array([1, 2, 3])    # Shape (3,)

r= a + b
r

array([[2, 4, 6],
       [5, 7, 9]])